language: go
go:
 - 1.6.2
install:
 - true
before_script:
 - go get golang.org/x/tools/cmd/vet
script:
 - export PATH=$PATH:$HOME/gopath/bin
 - ./deploy/check_style.sh .
 - go vet github.com/jiangshengwu/aliyun-sdk-for-go/...
 - go test -v github.com/jiangshengwu/aliyun-sdk-for-go/...
